version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: logbook-app
    container_name: logbook-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html:cached        # ✅ Tambahkan :cached untuk optimasi filesystem (khusus Mac/Win)
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini  # ✅ Tambahan untuk opcache
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy

  web:
    image: nginx:alpine
    container_name: logbook-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: logbook-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logbook
      MYSQL_USER: logbook
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql

volumes:
  mysql_data:
